import "server-only";

import type { Product } from "@/lib/store-config";

const accessoryProducts: Product[] = [
  {
    id: "accessory-pearl-shenandoah",
    sku: "PEARL-SHENANDOAH",
    name: "Pearl Mantels Shenandoah Wood Fireplace Mantel Shelf",
    slug: "pearl-mantels-shenandoah-wood-fireplace-mantel-shelf",
    description: "Rustic wood fireplace mantel shelf from Pearl Mantels. Available through Aaron's Fireplace Co. with sizing and finish guidance for your fireplace wall.",
    shortDescription: "Rustic Pearl Mantels wood mantel shelf for fireplace surrounds.",
    price: 0,
    contactForPricing: true,
    categoryId: "accessories",
    subcategoryId: "mantels",
    brand: "Pearl Mantels",
    images: ["/categories/mantels.jpg"],
    features: ["Mantel shelf", "Multiple sizes and finishes available", "Request quote for fit and availability"],
    specifications: { Brand: "Pearl Mantels", Type: "Mantel Shelf" },
    inStock: true,
    stockQuantity: 10,
    rating: 0,
    reviewCount: 0,
    isFeatured: true,
    isNew: false,
    isBestSeller: false,
  },
  {
    id: "accessory-pearl-zachary",
    sku: "PEARL-ZACHARY",
    name: "Pearl Mantels Zachary Wood Fireplace Mantel Shelf",
    slug: "pearl-mantels-zachary-wood-fireplace-mantel-shelf",
    description: "Pearl Mantels Zachary mantel shelf for a clean fireplace surround finish. Contact Aaron's for available sizes, finish options, and install planning.",
    shortDescription: "Clean-lined Pearl Mantels fireplace mantel shelf.",
    price: 0,
    contactForPricing: true,
    categoryId: "accessories",
    subcategoryId: "mantels",
    brand: "Pearl Mantels",
    images: ["/categories/mantels.jpg"],
    features: ["Wood mantel shelf", "Classic profile", "Sizing support available"],
    specifications: { Brand: "Pearl Mantels", Type: "Mantel Shelf" },
    inStock: true,
    stockQuantity: 10,
    rating: 0,
    reviewCount: 0,
    isFeatured: true,
    isNew: false,
    isBestSeller: false,
  },
  {
    id: "accessory-magra-hearth-pad",
    sku: "MAGRA-HEARTH-PAD",
    name: "Magra Hearth Fireplace Hearth Pad",
    slug: "magra-hearth-fireplace-hearth-pad",
    description: "Magra Hearth hearth protection for fireplace and stove projects. Aaron's can help confirm clearances, sizing, and the right hearth setup for your unit.",
    shortDescription: "Magra Hearth hearth pad and fireplace floor protection.",
    price: 0,
    contactForPricing: true,
    categoryId: "accessories",
    subcategoryId: "mantels",
    brand: "Magra Hearth",
    images: ["/categories/mantels.jpg"],
    features: ["Hearth protection", "Sizing and clearance planning", "Quote required"],
    specifications: { Brand: "Magra Hearth", Type: "Hearth Pad" },
    inStock: true,
    stockQuantity: 10,
    rating: 0,
    reviewCount: 0,
    isFeatured: true,
    isNew: false,
    isBestSeller: false,
  },
  {
    id: "accessory-skytech-1001t-lcd",
    sku: "SKY-1001T-LCD-A",
    name: "Skytech 1001T-LCD Fireplace Remote Control with Timer",
    slug: "skytech-1001t-lcd-fireplace-remote-control-with-timer",
    description: "Thermostatic Skytech fireplace remote control with LCD display and countdown timer for many gas fireplace and stove applications.",
    shortDescription: "Thermostatic fireplace remote control with timer and LCD display.",
    price: 0,
    contactForPricing: true,
    categoryId: "accessories",
    subcategoryId: "remotes-controls",
    brand: "Skytech",
    images: ["/products/parts/remote-ac.jpg", "/categories/remote-controls.jpg"],
    features: ["Thermostatic control", "LCD display", "Countdown timer"],
    specifications: { Brand: "Skytech", Type: "Remote Control", Model: "1001T-LCD" },
    inStock: true,
    stockQuantity: 10,
    rating: 0,
    reviewCount: 0,
    isFeatured: true,
    isNew: false,
    isBestSeller: false,
  },
  {
    id: "accessory-skytech-3301p2",
    sku: "SKY-3301P2",
    name: "Skytech Programmable Fireplace Remote Control",
    slug: "skytech-programmable-fireplace-remote-control",
    description: "Programmable fireplace remote control option for compatible gas fireplace systems. Contact Aaron's to confirm compatibility before ordering.",
    shortDescription: "Programmable fireplace remote control for compatible gas systems.",
    price: 0,
    contactForPricing: true,
    categoryId: "accessories",
    subcategoryId: "remotes-controls",
    brand: "Skytech",
    images: ["/products/parts/remote-elect-b.jpg", "/categories/remote-controls.jpg"],
    features: ["Programmable operation", "Compatibility check recommended", "Quote required"],
    specifications: { Brand: "Skytech", Type: "Remote Control" },
    inStock: true,
    stockQuantity: 10,
    rating: 0,
    reviewCount: 0,
    isFeatured: false,
    isNew: false,
    isBestSeller: false,
  },
  {
    id: "accessory-hht-rc200",
    sku: "2166-320",
    name: "Heat N Glo / Heatilator RC200 Fireplace Remote",
    slug: "heat-n-glo-heatilator-rc200-fireplace-remote",
    description: "Replacement fireplace remote for select Heat N Glo and Heatilator gas fireplace systems. Aaron's can help verify the correct remote before purchase.",
    shortDescription: "Replacement RC200-style fireplace remote for select HHT systems.",
    price: 0,
    contactForPricing: true,
    categoryId: "accessories",
    subcategoryId: "remotes-controls",
    brand: "Heat N Glo",
    images: ["/products/parts/ge-remote.jpg", "/categories/remote-controls.jpg"],
    features: ["Replacement remote", "Compatibility verification recommended", "Gas fireplace control"],
    specifications: { Brand: "Heat N Glo / Heatilator", Type: "Remote Control", Model: "2166-320" },
    inStock: true,
    stockQuantity: 10,
    rating: 0,
    reviewCount: 0,
    isFeatured: false,
    isNew: false,
    isBestSeller: false,
  },
];

export async function loadAccessoryProducts(): Promise<Product[]> {
  return accessoryProducts;
}
